services:

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    image: api-gateway:1.0
    container_name: api-gateway
    ports:
      - 8000:8000
    env_file:
      - ./api_gateway/.env
    environment:
      PYTHONPATH: /app:$PYTHONPATH
      PYDEVD_DISABLE_FILE_VALIDATION: 1
    volumes:
      - ./api_gateway:/app
    restart: unless-stopped
    networks:
      - microservices-api

  auth-service:
    build:
      context: ./auth_service
      dockerfile: ./Dockerfile
    image: auth-service:1.0
    container_name: auth-service
    ports:
      - 8001:8000
    env_file:
      - ./auth_service/.env
    volumes:
      - ./auth_service:/app
    restart: unless-stopped
    depends_on:
      - auth-db
    networks:
      - microservices-api

  auth-db:
    image: postgres:15
    container_name: auth-db
    ports:
      - 5440:5432
    env_file:
      - ./env/.auth_service_db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - microservices-api

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    env_file:
      - ./env/.mailpit.env
    volumes:
      - mailpit_data:/data
    restart: unless-stopped
    networks:
      - microservices-api

volumes:
  pg_data:
  mailpit_data:

networks:
  microservices-api:
    driver: bridge
